name: Auto Update README

on:
  schedule:
    - cron: '*/2 * * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Add exclamation mark to README
        run: |
          sed -i "s/Made with ❤️ for learning and automation!!\+/&!/" README.md
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: add ! to README" || echo "No changes to commit"
          git push origin dev
      - name: Create Pull Request to main
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: add ! to README"
          branch: dev
          base: main
          title: "Automated PR: Add ! to README"
          body: "This PR was created automatically to add an exclamation mark to the README."
          delete-branch: false
      - name: Auto-merge PR
        if: steps.cpr.outputs.pull-request-url != ''
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'dev',
              base: 'main',
              state: 'open',
            });
            if (pr.data.length > 0) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.data[0].number,
                merge_method: 'merge',
              });
            }
