name: Simple CI/CD

on:
  push:
    branches:
      - main
    # Only run if the push is a result of merging from dev to main
    # This uses a condition in the job to check the source branch

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.head_commit.message == 'Merge branch 'dev'' || contains(github.event.head_commit.message, 'Merge pull request')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Say Hello World
        run: echo "Hello, World! CI/CD triggered by merge from dev to main."
